### ISSUE TITLE
Catch up meeting 18th June

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#112]
https://meet.google.com/pbx-tztm-egm

**Agenda**

- [x] Review project progression [here](https://github.com/neontribe/www/projects/5)
- [x] Discuss any outstanding PRs
- [x] Look at the kimai codes.
- [x] Review the current situation with the copy
- [x] Discuss if deadline of 28th of June is still feasible
- [x] Set out plan to get images/info from people for the tribe page
- [x] Discuss have the selected projects been chosen yet?
- [x] Discuss typeface options
- [x] Is a privacy page needed?
- [x] Is the carousel on the front page only featuring three stories?

**Comment by katjam** [comment]
**Actions**

- [ ] @harryharrold can we use one code for logging time? If not, we'll need to look at the categories again so they are relevant for this stage.
- [ ] @harryharrold @katquatermass to give update on where we are with copy and if they need help.
- [ ] @r

**Comment by katjam** [comment]
Current Kimai

![image](https://user-images.githubusercontent.com/861172/59677146-1d6e6300-91c1-11e9-8a95-a5e66677c307.png)

**Comment by katjam** [comment]
@alexalala Wasn't sure if you were volunteering to do the people doc... if not don't worry - but if you do have time, then pleas put your name on the action.

**Comment by HedgehogHolly** [comment]
Also, attendance: @HedgehogHolly @katjam @amandaneontribe @RpprRoger and @alexalala

**Comment by katquatermass** [comment]
Project content is in this page here https://docs.google.com/document/d/17n2_cD1UF0xKNQha9e2FOMKyZDesoNCFdTOIQbhiHqE/edit#heading=h.jdxcd73hkc5d

I don't have time to do more for 28th but 5 projects are ready to go I think once a dev from each one has said "yes that's what we do" and Karl or Rose has done a "I'm a detail person" proof read.

**Comment by katquatermass** [comment]
The "what people's content should be" discussion is on #68

**Comment by HedgehogHolly** [comment]
Current copy list (MVP)

- [ ] Minimum 5 Projects headline, description, problem and solution: [google docs](https://docs.google.com/document/d/17n2_cD1UF0xKNQha9e2FOMKyZDesoNCFdTOIQbhiHqE/edit#heading=h.c58z51egi52a) (**done but needs to be signed off**)
- [ ] The Tribe bios: [google docs](https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit)
- [ ] Core values: issue #55 (@harryharrold) 
- [ ] The three stories: #56 (@roseb04) 
- [ ] Our work intro: issue #57 (@harryharrold)
- [ ] The tribe intro: issue #67  (@harryharrold)
- [ ] Join the tribe: issue #69 (@harryharrold)
- [ ] Join the tribe form/survey: issue #92 (@harryharrold are we still doing a form? someone needs to set it up)
- [ ] Privacy and legal page: issue #115 (@neil-dabson)

Copy list (Full build?)

- [ ] Speaking based projects: issue #74

**Comment by roseb04** [comment]
@roseb04 to get sign off from the Haven
