### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#189]
### Plan
- [x] Remove/move the quickstart section in the readme. 
- [ ] Improve documentation for how deploys work - created issue https://github.com/neontribe/www/issues/306 for this
- [x] Add contributing documentation
- [x] browser support list, evergreen + ie11 https://github.com/neontribe/www/issues/232
- [ ] Write up plan for  ongoing work - created an issue for this: https://github.com/neontribe/www/issues/307
- [ ] Write up card triage process - covered in this issue: https://github.com/neontribe/www/issues/307

**Comment by roseb04** [comment]
Created a wiki for the browser list: https://github.com/neontribe/www/wiki/Supported-browsers

**Comment by roseb04** [comment]
Closing because have carded out tasks into the following issues: https://github.com/neontribe/www/issues/307 and #306
