### ISSUE TITLE
Browser bugs to fix

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#229]
### Edge bugs
- [x] [Carousel images too big](https://github.com/neontribe/www/issues/218#issuecomment-507700654) and again [#2](https://github.com/neontribe/www/issues/218#issuecomment-507701967)
- [x] [Triber card inconsistencies](https://github.com/neontribe/www/issues/218#issuecomment-507695714) here too [#2](https://github.com/neontribe/www/issues/218#issuecomment-507692005)
- [x] [Triber card spinning diagnally](https://github.com/neontribe/www/issues/218#issuecomment-507694918)
- [x] [Left aligned squiggle](https://github.com/neontribe/www/issues/218#issuecomment-507693837)
- [x] [Triber card grid](https://github.com/neontribe/www/issues/218#issuecomment-507694125)

### Firefox bugs
- [x] [Carousel images too big](https://github.com/neontribe/www/issues/218#issuecomment-507713215)

**Safari iPad**

Testing on https://neontribe-www-git-229-browser-bugs.neontribe.now.sh/the-tribe

- [x] No imagery in white hexagons. Logo, carousel images, social good images
![Screenshot_070319_104134_AM](https://user-images.githubusercontent.com/4446325/60581630-20e81980-9d7f-11e9-8702-4d0def41fe45.jpg)

**Carousel behaviour**

- [x] Images not moving in correllation to the text related to the image.
![Screenshot_070319_105026_AM](https://user-images.githubusercontent.com/4446325/60582266-5e00db80-9d80-11e9-8ba7-d4e6a334fb28.jpg)

- [x] Double tapping the left/right carousel arrows increases page size (intermittent)
![Screenshot_070319_112246_AM](https://user-images.githubusercontent.com/4446325/60584339-e6817b00-9d84-11e9-985b-8d01a72a555a.jpg)

- [x] Text and images seem very slightly left aligned, noticeably on the Tribe page
![Screenshot_070419_112107_AM](https://user-images.githubusercontent.com/4446325/60659656-da152500-9e4d-11e9-9eb3-2f9e23f25b62.jpg)

![Screenshot_070419_112331_AM](https://user-images.githubusercontent.com/4446325/60659784-26f8fb80-9e4e-11e9-988c-f498bc7acdbd.jpg)

### IE11

- [x] Triber grid https://github.com/neontribe/www/issues/232#issuecomment-508117694
- [x] Card flip https://github.com/neontribe/www/issues/232#issuecomment-508117694
- [x] Blogs https://github.com/neontribe/www/issues/232#issuecomment-508133883

- [x] Tribe - Images squashed (Toby in particular)
- [x] Tribe - Text escaping from under the image
- [x] What we do images squashed

**Comment by jermyk** [comment]
@r Tested above issues. All look good. Still no b/w images on IE11 however.

**Comment by jermyk** [comment]
@RpprRoger

Above issues tested successfully for IE11 and Safari
