### ISSUE TITLE
Browser bugs

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#230]
### Bugs:
- [x] [Triber images don't revert to b&w on blur](https://github.com/neontribe/www/issues/218#issuecomment-507715031) - #311

**Safari - iPad air**
- [x] Privacy policy page rendering compared to Chrome #312
![Screenshot_070319_111321_AM](https://user-images.githubusercontent.com/4446325/60583793-9229cb80-9d83-11e9-9273-191fb02401b0.jpg)

- [x] The Tribe page flip still looks a bit flaky. User can see a reverse image for a split second when returning from text to image. #310

**Android - Samsung Galaxy J600FN**
- [x] Minor styling issue with buttons
![Screenshot_070319_120145_PM](https://user-images.githubusercontent.com/4446325/60586610-53e3da80-9d8a-11e9-85d9-0b9f8ae7c9d0.jpg) #313

- [x] Red box appears around nav buttons when active
![Screenshot_070319_011545_PM](https://user-images.githubusercontent.com/4446325/60590770-c3f75e00-9d94-11e9-9256-023760145198.jpg) #314

#### IE11:
- [x] Full colour images, no b&w filter https://github.com/neontribe/www/issues/232#issuecomment-508117694 #311
- [x] Active page signifier https://github.com/neontribe/www/issues/232#issuecomment-508117694 split in #297 
- [x] Card disappears briefly during flip #310
![image](https://user-images.githubusercontent.com/32434620/60649685-674e7e80-9e3a-11e9-9ded-d499f1275f85.png)
- [x] Profile words can escape cards - no longer reproducible 01/10/19
![image](https://user-images.githubusercontent.com/32434620/60649847-c6ac8e80-9e3a-11e9-96df-9068f360b801.png)
- [x] Aspect ratio of images not respected -- not an issue anymore (looks fine as of 19.09.2019)
![image](https://user-images.githubusercontent.com/32434620/60649889-e348c680-9e3a-11e9-8752-789d1aed2aa2.png)
- [x] Header menu very spread out and logo is lower on the page #309
![logo-placement-homepage](https://user-images.githubusercontent.com/29477363/65252677-50423300-daf1-11e9-91ea-73bbc9b9a91b.png)
- [x] No squiggle seperator #308

**Comment by zii-67** [comment]
E11:

- [ ] the twitter/github/LinkIn icons aren't sat in the middle.   ##[](url)
![Screenshot from 2019-09-13 15-14-48](https://user-images.githubusercontent.com/54798712/64869592-89822b00-d639-11e9-824d-9e1ba3c8a6a1.png)

**Comment by Nikomus** [comment]
All items individually carded.
