### ISSUE TITLE
Revisit meta-descriptions to make them more charity friendly

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#234]
Current content:

Up to 160 characters.

Main: "Neontribe is a digital agency. We learn from users, build something small, then measure how that’s helped. We hit deadlines, and make best use of your budget.”

Tribe: “Neontribe is a digital agency. Why neon? It’s the colour of tech. Why tribe? Individuals collaborating, hand-making useful tools that do a job of work.

Works: “Neontribe is a digital agency. We research for context. We design for use. We code to completion. We test to exhaustion. Then we engineer enhancement.

**Comment by katquatermass** [comment]
- [ ] See what google is showing once site is live (no point working on crafting with care, if nothing is using them anyway)
- [ ] People to suggest other places to check whether they are being referenced? Twitter/Facebook sharing?
- [ ] @katquatermass Kat to do charity facing drafts IF meta-description is being used
