### ISSUE TITLE
Catch-up meeting 27 August

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#281]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #274
- [x] Review actions from #278
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board

**Actions**
- [ ]  @RpprRoger to continue to document process for ongoing neontribe web development #189
- [ ] Documentation of process on #189 -  @roseb04 to speak to @harryharrold and whoever else is interested to update them on the new process
 - [x] @nikomus Remind folks about washup when it's one week away
