### ISSUE TITLE
Catch-up meeting 03 September

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#283]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #281
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board

**Actions**
- [ ] @RpprRoger and @HedgehogHolly to continue to document process for ongoing neontribe web development #189
- [ ] Documentation of process on #189 - @roseb04 to speak to @harryharrold and whoever else is interested to update them on the new process
