### ISSUE TITLE
Catch-up October 1st

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#305]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from before
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board

**Actions**
- [x] Split #189 into separate issues and prioritise - @roseb04 to do
- [x] Take completed parts of #189 and publish where they should be - @roseb04 to look into this
- [x] Finish splitting #230 into individual tickets @Nikomus 
- [x] Work on #267 to be clearer what to do @Nikomus 
- [x] Tidy up wash-up ticket #282 @Nikomus

**Comment by katjam** [comment]
Actions complete
