### ISSUE TITLE
Catch up November 12th

### ISSUE THREAD

**Issue by katjam** [neontribe/www#329]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #305, #315, #319 , #327 
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board, order/review (started but ran out of time)
- [x] Are @katquatermass new issues in the right place to be prioritised - yes added to backlog milestone which is where we pluck stuff for the ongoing work board

**Actions**
- [x] @katjam  Make sure there is a card for the documentation of process - so we aren't relying on only Rob to have time to write it down. Make notes on the cards: https://github.com/neontribe/www/issues/306, https://github.com/neontribe/www/issues/307
- [x] @Nikomus Ask relevant people to review https://github.com/neontribe/www/pull/324 and https://github.com/neontribe/www/pull/325 and https://github.com/neontribe/www/pull/326
- [x] @HedgehogHolly chase people to review her favicon designs
- [x] @HedgehogHolly consider closing https://github.com/neontribe/www/issues/184

**Comment by katjam** [comment]
@Nikomus Did you get a chance to ask people for reviews? If not please port your task to #330

**Comment by katjam** [comment]
@HedgehogHolly Did you get any feedback on the favicon designs? If not, please port your task to #330 so we don't have to keep both issues open.

**Comment by katjam** [comment]
@HedgehogHolly I think we agreed that #184 could be closed, but if you have time please check and close if you are still happy to do so.

**Comment by HedgehogHolly** [comment]
Yes, I did say we could close #184. I'll do that now.

I've done another Fav Icon but it doesn't really work without the text.
