### ISSUE TITLE
Catch-up December 10th 

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#340]
**Plan**

- [x] Review incomplete actions from #339
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board, order/review

**Actions**

- [x] @RpprRoger  Check with Nick and Katja about outstanding tasks
    - [x] @Nikomus to tidy IE SVG branch
    - [x] @katjam chase old issues in backlog - determine if we need discussion or can close as won't fix. Would be nice to keep out backlog under 35 issues. @jermyk volunteered to help.
- [x] @RpprRoger merge #326 
- [x] @RpprRoger propose a solution to #325 
- [x] @RpprRoger propose a tuesday talk about now.sh, to feed into #306 
- [ ] @RpprRoger to check in on "@jermyk chase old issues in backlog - determine if we need discussion or can close as won't fix. Would be nice to keep out backlog under 35 issues."
- [ ] @HedgehogHolly to review #324
