### ISSUE TITLE
Catch-up 7 January

### ISSUE THREAD

**Issue by katjam** [neontribe/www#344]
**Plan**

- [x] Review incomplete actions from #342 
- [x] Discuss any outstanding PRs
- [ ] Go through the backlog/project board, order/review

**Actions**

- [x] Get all the info and assets we need from @HedgehogHolly that we need before she leaves (assets in Neontribe visual resources in Nextcloud)
- [x] @katjam to organise cull in backlog would be nice to keep to 35 issues
- [ ] @katquatermass Add to process doc things get moved to the todo list, during the catchup we could add a note for why it's bumped to "todo" carried forward to #347
- [ ] @katquatermass Speak to @RpprRoger about getting contributors doc finished and resolve comments https://github.com/neontribe/www/pull/338/files carried forward #347

**Comment by katjam** [comment]
I have made some notes on the issues without milestone - to prompt people to action or close. There are 6 PRs which should take care of closing some of the backlog issues.

We are near the 35 mark.

If we are able to ditch the `to do` column as I suggest in https://github.com/neontribe/www/issues/347#issuecomment-574095858

It will become easier to do the sorting exercise. We can also consider a process whereby we periodically mark issues with `consider closing` label and give people a couple of weeks to veto that.

**Comment by katjam** [comment]
Closing with actions carried forward as @RpprRoger is ill.
