### ISSUE TITLE
Catch up 3rd March

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#363]
**Plan**
- [x]  Rose and Rachel to talk about website review 
- [x] Harry to talk about product owning 
- [x] Review incomplete actions from #[362] and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.
- [x]  Rupert requesting #15 to be promoted to top stories (and removing its reliance on #14 as a prerequisite)
- [x]  Katja requesting issue to be raised and put to top priority removing images of staff who have left

**Actions**

- [x]  @zii-67 will work on #15 with @marxian when she next in Norwich
- [x]  @zii-67 will raise an issue for removal of staff images.
- [ ] @katquatermass and @RpprRoger are part way through documentation and will continue
Documentation improvements 
- [ ] @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [ ] @zii-67 will get copy and design for inside of cookie consent banner agreed with @roseb04 and @rachelpeharding for #207

**Comment by harryharrold** [comment]
re: Product owning. Is about, but not simply about, decision making, it is also about communicating a vision such that the decision making needs not happen so often. Our original feelings for the project still remain - it seems there's a disjoint between the technical work and the larger vision which is causing project fail. Maybe this is a roadmapping issue? Or an internal comms issue?

Why don't we stop - we're not done. What have we not done - we've not met our goals. What goals? The stories expressed on our initial research. So specifically - what are those stories... Would it be useful to split them down?

If you ask someone why they are doing a task - can they given you a compelling answer?

**Comment by katjam** [comment]
Pushing actions forward to #402  and closing.
