### ISSUE TITLE
Catch-up 17 March

### ISSUE THREAD

**Issue by katjam** [neontribe/www#402]
**Plan**

- [x] Review incomplete actions from #362 #363 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review _Leaving auto PRs until we know process for merging, and leaving other PRs until they are ready_
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward. 
- [x] Discuss prioritising #401 

**Actions**

- [ ] Carried forward 3 weeks:  @katquatermass and @RpprRoger are part way through documentation and will continue
Documentation improvements
- [ ] Carried forward 3 weeks:   @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [ ]  @zii-67 will get copy and design for inside of cookie consent banner agreed with @roseb04 and @rachelpeharding for #207
- [x] @amandaneontribe to discuss recruitment process. The form isn't working for the strategy she'd like to be using. Also like to do some testing to see if users can find the join info easily enough. We have it after Join the Tribe because we designed the journey to encourage people to 'Meet the tribe' before deciding to join. But maybe we are missing out on good candidates because we don't advertise that we are hiring. [Trello card created here](https://trello.com/c/cTjv5KJH/123-recruitment-is-our-current-interview-process-as-effective-as-we-wished)

Update from @zii-67 :
> - The cookie consent content have included inside I will make it looks better and push onto GitHub to let everyone see in tis week. 
> - Auto dependencies bot have created by me and Rupert (seems to work well). All the dependencies in PR section were created by default. The one with :ballot_box_with_tick: are allgood dependencies that does not affect the outcome /preview of the website. The one with error :negative_squared_tick: we can just ignore it as it will affect the preview.
> - Some PR I've merged such as: Remove Alex.jpg and Andy. 
> - Dependencies PR can be merged once another people approve and agree with it.

**Comment by katjam** [comment]
@marxian Is it ok to merge the auto PRs as long as the deploy isn't broken? Or do you have a more careful process for it?

**Comment by Nikomus** [comment]
![image](https://user-images.githubusercontent.com/32434620/76856157-967f1180-684a-11ea-85ae-8cea0b4b0c09.png)

**Comment by katjam** [comment]
Closing and moving un-done actions forward
