### ISSUE TITLE
Catch-up 24 March

### ISSUE THREAD

**Issue by katjam** [neontribe/www#409]
**Plan**

- [x] Review incomplete actions from #402 and decide whether to carry over or change the action
- [ ] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**
- [x] Ask team if we can move this meeting to another day so @RabidGamer  can get involved
- [ ] Carried forward 4 weeks:  @katquatermass and @RpprRoger are part way through documentation and will continue
Documentation improvements
- [ ] Carried forward 4 weeks:   @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [x]  @zii-67 will get copy and design for inside of cookie consent banner agreed with @roseb04 and @rachelpeharding for #207
- [x] @katjam Add discuss review strategy for renovate bot PRs at next meeting. @marxian has some experience and ideas.

**Comment by katjam** [comment]
@katquatermass @robpre @zii-67 @roseb04 @rachelpeharding  Please update here if any of your actions can be marked complete.

**Comment by katjam** [comment]
@katquatermass @robpre @zii-67 Please tick if complete and or add further action to #420 in prep for this week's meet.
