### ISSUE TITLE
Catch-up meeting 5 Feb 2019

### ISSUE THREAD

**Issue by katjam** [neontribe/www#41]
**Actions from meeting**

**Plan**
- [ ] @katquatermass  will organise getting evidence gathered from Flow and MVP prototype sessions #40 
- [ ] @HedgehogHolly  will move forward with the challenge/ solution prototype #39 
- [ ] @HedgehogHolly  (with support from @gingerbreadpup ) will use @katquatermass' documentation of the Flow and MVP sessions (#40) to create the rest of the MVP in paper.
- [ ] @roseb04  will look at moving on with the social media stuff - #5 #7 #4 #6  (with tech help from @andybarnes  and access from @harryharrold )
- [ ] People with spare bits of time will look at the 6 or so code tasks that need doing as prep (https://github.com/neontribe/www/projects/1) 

It was also decided so that we don't wear out our favours in Norwich that Exeter people will test the MVP (once complete)
