### ISSUE TITLE
Catch-up 1 Apr

### ISSUE THREAD

**Issue by katjam** [neontribe/www#420]
**Plan**

- [x] Review incomplete actions from #409 and decide whether to carry over or change the action
- [ ] Discuss review strategy for renovate bot PRs at next meeting. @marxian has some experience and ideas
- [ ] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**
- [ ] Carried forward 4 weeks:  @katquatermass and @RpprRoger are part way through documentation and will continue.
- [x] @Nikomus will identify the issue for that documentation work.
- [ ] Carried forward 4 weeks:   @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [ ] Cookie consent - https://github.com/neontribe/www/issues/421 and PR https://github.com/neontribe/www/issues/207

**Comment by roseb04** [comment]
Commented on issue #42: 

> We are happy with the design @zii-67 and how it looks, a few things:
> 
> - Make sure it is mobile responsive
> - If the 'accept/decline' buttons could look and feel like the other neontribe buttons on the site that would be great, but not necessary
> - Make sure the Katja's face isn't floating through the banner
> 
> We are thinking we would like the set a deadline of this week to finish the work on this (Friday 3rd April)

**Comment by Nikomus** [comment]
The issue for further work on docs is https://github.com/neontribe/www/issues/307
