### ISSUE TITLE
Apr 8 Catch Up.

### ISSUE THREAD

**Issue by harryharrold** [neontribe/www#422]
**Plan**

- [x] Review incomplete actions from #420 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**
- [ ] Carried forward 4 weeks:  @katquatermass and @RpprRoger are part way through documentation and will continue on #307
- [ ] Carried forward 4 weeks:   @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [ ] Cookie consent - @RabidGamer is on https://github.com/neontribe/www/issues/421 and PR https://github.com/neontribe/www/issues/207
- [ ] Schedule a review strategy for renovate bot PRs at next meeting. @marxian has some experience and ideas

**Comment by Nikomus** [comment]
Closing as actions passed forward.
