### ISSUE TITLE
May 6th Catch-up

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#428]
**Plan**

- [x] Review incomplete actions from #426 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [ ] Carried forward 6 weeks - Schedule a review strategy for renovate bot PRs at next meeting. @marxian has some experience and ideas
- [ ]  Carried forward 8 weeks: @katquatermass and @RpprRoger are part way through documentation and will continue on #307
- [ ] Carried forward 8 weeks: @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [ ] @Nikomus to review any styling and accessibility issues on #207 and complete with @zii-67 and/or @RabidGamer
