### ISSUE TITLE
May 20th Catch-up

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#431]
**Plan**

- [x] Review incomplete actions from #428 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [x] Carried forward 8 weeks - Schedule a review strategy for renovate bot PRs at next meeting. @marxian has some experience and ideas https://github.com/neontribe/www/wiki/How-we-prefer-handle-auto-update-pull-requests
- [ ]  Carried forward 10 weeks: @katquatermass and @robpre are part way through documentation and will continue on #307
- [x] @zii-67 to check if #348 needs any further integration with other docs
- [x] @zii-67 to PR for #207 this week
- [x] Complete #430 to add Rachel to The Tribe page

**Comment by zii-67** [comment]
I think it's been done since I can see the the PR is merged into master branch.

**Comment by katjam** [comment]
Carried doc action forward.
