### ISSUE TITLE
Catch up Meeting 19 Feb 2019

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#44]
**Progress**

**Agenda**
- [ ] Report on actions from #42
- [ ] Detailed MVP convo to advance the prototype based on q's on #43

**Actions**
- [ ]  Make a plan for usability testing prototype in Exeter @katjam
- [ ]  @HedgehogHolly to look at possible trips to Exeter to take part in final prototype shaping and testing sessions
- [x]  @HedgehogHolly to build additional wireframes based on last comments on #43
- [ ] @katjam and @Nikomus to transfer into paper prototype

**Comment by HedgehogHolly** [comment]
Updated wireframe https://github.com/neontribe/www/issues/43#issuecomment-465940423

**Comment by katjam** [comment]
@HedgehogHolly to visit week of 4 or 11 March. We will update prototype on the Monday and test on the Tuesday.
