### ISSUE TITLE
Catch-up 19th August

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#467]
**Plan**

- [x] Review incomplete actions from #457 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [ ] @Nikomus Think about moving build logs to be accessible by a group email account
- [ ]  Carried forward 13 meetings: @katquatermass and @robpre are part way through documentation and will continue on #307
- [ ] @katjam pick off more auto bot PRs and encourage them gently in
- [ ] @katjam and @Nikomus looking through #465

**Comment by katjam** [comment]
@katquatermass and @robpre do we need to keep pushing that action for documentation forward or shall we shelve until you have time to pick up again?

**Comment by katjam** [comment]
Carried actions forward to #473
