### ISSUE TITLE
Catchup meeting 7th May 

### ISSUE THREAD

**Issue by charlesstrange2** [neontribe/www#54]
**What needs doing?**
https://meet.google.com/fnw-uqxr-bhw

**Agenda**
- [ ] Go over current issues and make sure they still make sense

- [ ] Review incomplete actions from #52  below:

**Actions from #52 **

- [x] Set next date - Tuesday before standup;  in a fortnight - make a calendar entry - @charlesstrange2 Make Catch-up issue for the next one.
- [ ] Round of design checking PR (companywide) #70 
- [ ] Review @ob6160 PR about wordpress/gatsby (companywide)
- [x] Create copy issues based on design @HedgehogHolly 
- [ ] Harry will product own for this next stage
- [ ] @HedgehogHolly  to work on item 4 of card #51 "Produce UI then decide what other support structures are needed to get it to a live deploy"
- [x] Create a space to make the website public; github pages - @HedgehogHolly (also ask @katjam)
- [x] setup milesotne "Public release by July" - Harry

**Actions**
- [x] Set next meeting date (weekly again - 11:45)
- [x] Designate another product owner
- [ ] @alexalala can take a look at some of the Gatsby code
- [ ] Ollie's pr needs review - we may not need wordpress integration right now
- [x] #75 Problem solution - info needs copy work. We thought about replacing the description with this 'more creative copy' The problem solution was originally a clever teaser and it doesn't fit as a concept on the projects page itself. How many blocks of text?
@katquatermass @roseb04 ? Chase some of the copy issues - particularly the How we work page - but also people.
- [x] @katjam make some issues off design conversations.
- [ ] @katjam  Go over current issues and make sure they still make sense - we didn;t have time to do this as a group in the meeting.

**Comment by katjam** [comment]
Attending:
@katjam @HedgehogHolly @alexalala @falconx Amanda
