### ISSUE TITLE
Catch up meeting 14th May

### ISSUE THREAD

**Issue by katjam** [neontribe/www#76]
https://meet.google.com/pbx-tztm-egm

**Agenda**
- [x]  Review actions from #54 
- [x] Discuss any outstanding PRs
- [x] Make sure issues & milestones are still current
- [x] Discuss progress on MVP design (raw branch) - including issues #71, #72, #73, #74, #75

**Notes From Meeting**
- Product owner this week @HedgehogHolly 
- Discussed #79 - happy with second version of illustration
- Discussed #71 - the three words on the front might be too crowded, other experimentation is needed
- Discussed #72 - happy with change
- Discussed #73 - happy with change
- Discussed #75 - all on call agreed that problem and solution was the way to go, removing the description and quote. New design for the how we work page is needed
- Ollie's PR still needs a review
- Next meeting will be **Tuesday 21st May 11.30am** - meet.google.com/pbx-tztm-egm

**Next Actions**
- [x] @HedgehogHolly continue to improve on #71, try other options like the words fading in/out on hover/focus
- [x] @HedgehogHolly  change line length on the wider paragraphs #81 
- [x] @HedgehogHolly to work on How We Work page to show new agreed problem and solution 
- [ ] @alexalala and @RpprRoger to look at Ollie's PR #53 
- [x] @HedgehogHolly list general fixes that need to be done - (#87 List of small fixes)
- [ ] Set next date for meeting
- [ ] Set new product owner

**Comment by HedgehogHolly** [comment]
attendance: @alexalala @falconx @roseb04 @amandaneontribe @HedgehogHolly
