### ISSUE TITLE
Catch up meeting 11th June 

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#88]
https://meet.google.com/pbx-tztm-egm

**Agenda**
- [ ] Review actions from #82  
- [ ] Discuss any outstanding PRs
- [ ] Make sure issues and milestones are still current
- [ ] Discuss progress on MVP design - issues #71 #75 
- [ ] Review the list of small fixes #87
- [ ] Set date for next meeting 

**Notes From Meeting**

**Next Actions for 11th June**

**Comment by HedgehogHolly** [comment]
### Notes from meeting with Rich

**Front Page**
- Illustration isn't working for the front page, it shows mechanics rather than an end state, it might work better on the How We Work page
- The strap line should be more of a focus on the front page, maybe removing the image will help, or putting it before an image rather than after
- The strap line should be short and to the point
- The eye is drawn to the photograph of a person rather than the illustration

**The Tribe**
- The hover effect was expected to be neon or pop-y colours, its almost jaring to see the 'real-life' colours

**How We Work**
- How we work page isn't the correct wording, a process page is expected rather than who we have worked with/projects
- Reduce the number of projects
- There is a cognitive overload, with extra thinking needed to read the white text on black and see the ghost image, with the bright colours
- Try out a newspaper style headline approach for describing the projects
- Images should be smaller? don't add enough to warrant a 50:50 split with problem/solution

**General**
- Put the logo in a hexagon
- Maybe look at what we do like about the live neon tribe site
- Theres the neon aspect reflected in the design but theres no tribal aspect
- Could the logo be on the front page 
- "handmade", "family", "trust", "wholesome" "we solve your problems digitally"
- Maybe look at more tribal or expressive fonts for the headers

**Comment by harryharrold** [comment]
(Good write up - I had one more general comment, which is that we should consider making the design more consistent across the pages; reducing our visual language. *Specifics* on that would be that:

We use a lozenge with a soft gradient edge in only one place - can we replace that with a design style that we use elsewhere?

We use "boxed black text on white" to give more information on a person - and "black text on white" to give more information on a project - is that one more style than is required? (qv: cognitive load observation above?

**Comment by RpprRoger** [comment]
I created #97 to track the work on the design

**Comment by katjam** [comment]
@HedgehogHolly When you (or someone) makes the next catch-up card, please add a list item to look at the kimai codes I don;t think they make sense anymore.

Are we able to close this issue and the previous May one? Or they have outstanding actions?
