### ISSUE TITLE
Prepare projects copy

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#98]
Non-exhaustive list of projects:
- The Great British Toilet Map
- Innovation Labs
- A Day In The Life
- Docready
- Allegiant
- The Haven
- seAp
- Alexandra Rose
- Mind Of My Own
- Open Ag
- NCVO
- Open Data Studios
- UKFC
- Addaction

## Tasks

- [x] Write headlines for the projects NT has worked on
- [x] Pick 5 favourite
- [x] Prepare full copy for the 5

## Copy structure

- [x] Write a Headline for the projects
- [x] Write a short summary line
- [x] Write a problem and solution 

### Related user stories
- As Brian, Jess and Terrance, I want to get the impression that Neontribe know what they are doing so that I feel confident in working with them.
- As Brian, I want to understand the process neontribe use to deliver projects so that I feel confident they can deliver on our project.

**Comment by HedgehogHolly** [comment]
https://docs.google.com/document/d/17n2_cD1UF0xKNQha9e2FOMKyZDesoNCFdTOIQbhiHqE/edit#heading=h.jdxcd73hkc5d
